# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeelGood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FeelGood
  pod 'Anchors'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'RxOptional'
  pod 'DefaultsKit'
  pod 'Reveal-SDK'
  pod 'SwiftLint'

  target 'FeelGoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeelGoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
